### ISSUE TITLE
Latest cgminer-ants1-4.9.1a-581b5e1 API issue

### ISSUE THREAD

**Issue by michelem09** [kanoi/cgminer-binaries#9]
I can't connect to API if I use the latest cgminer-ants1-4.9.1a-581b5e1, I'm getting a "socket_read(): unable to read from socket [104]: Connection reset by peer" from my PHP script.
This doesn't happen with the previous version.

**Comment by kanoi** [comment]
You'll need to provide more details - do it on the forum.
https://bitcointalk.org/index.php?topic=28402.0
i.e. what previous version and what API/allow settings and network have you setup.
The API is the same as my previous version except it now includes the IPv6 patch - so that patch may or may not be causing your specific problems.
API worked fine in all my testing.
It's the same API as in master cgminer, so if there is a problem, the same problem will be in cgminer everywhere - so report it on the forum and I'll look into it.

**Comment by michelem09** [comment]
With this cgminer-ants1-4.3.2a-85fcf0c I haven't any problem.

As soon as I switch to 4.9.1a I start having this API issue.

Options are the same, I only changed the binary:

        option api_allow 'W:127.0.0.1,W:192.168.1.0/24'
        option api_listen '1'
        option api_network '1'

I'm investigating

**Comment by michelem09** [comment]
Port (default 4028) seems to be open:

```
nmap -p4028 192.168.1.99

Starting Nmap 4.68 ( http://nmap.org ) at 2015-05-04 10:05 CEST
Interesting ports on 192.168.1.99:
PORT     STATE SERVICE
4028/tcp open  unknown
```

But trying a telnet (also from the Ant/Localhost) doesn't work:

    root@antMiner:/usr/bin# telnet 192.168.1.99 4028
    Connection closed by foreign host

**Comment by kanoi** [comment]
Try R:0/0 just to see if the API itself is still OK.
I'm guessing that the subnet code was broken by the IPv6 changes.

**Comment by michelem09** [comment]
Ah great! That did the job! So api_allow subnet must be set to 0/0 not to the LAN subnet:

    option api_allow 'W:127.0.0.1,W:0/0'

Thanks!

**Comment by kanoi** [comment]
No, that's probably a bug.
0/0 means anyone can access it.
I'll look into the subnet changes/problem and see if that code is the cause.

**Comment by michelem09** [comment]
Yes it is sure a bug, I was telling that for who want to use this release in the meanwhile you can fix it. Of course keeping 0/0 is not the best thing specially if your system is in the public internet (I'd keep away from it). But while you keep it in your LAN only you can live with it waiting for the next release ;)

**Comment by kanoi** [comment]
Pity this is 9 comments so far here rather than on the forum where everyone would see it ...
Anyway, can you check you have the correct subnet?
I've (so far) been unable to find the bug, but testing on my S1 shows no problem also when I use
"W:127.0.0.1,W:192.168.1.0/24"
This will tell you the subnets on your S1
 ifconfig | grep inet
If you do have all those network numbers correct, then either post on the forum on visit IRC, coz tracking down the problem will take some effort since it doesn't happen for me.

**Comment by michelem09** [comment]
inet addr:192.168.1.99  Bcast:192.168.1.255  Mask:255.255.255.0

The net is right because it shouldn't work with the previous version too, while it works.

I really don't know what happened but now I just changed the api_allow option to previous one with LAN subnet and it works...

**Comment by kanoi** [comment]
API issue found - cause was (as I originally thought) the IPv6 changes
The problem was that 192.168.1/24 would fail instead of being padded to 192.168.1.0/24
API now reports to the consol bad IP addresses that are ignored
Next S1 release (soon) will have the updated cgminer with this fix.
As a workaround simply pad out the IP address fully

**Comment by kanoi** [comment]
API address fix updated
https://github.com/kanoi/cgminer-binaries/commit/ba639587b2533dd363dd10a9b1392744080236c0
https://github.com/kanoi/cgminer-binaries/tree/master/AntS1
